services:
  ocserv:
    build: .
    container_name: ocserv-docker
    restart: unless-stopped
    
    # Привилегированный режим для настройки сети
    privileged: true
    
    # Загрузка переменных окружения из .env файла
    env_file:
      - .env
    
    # Порты
    ports:
      - "443:443/tcp"
      - "443:443/udp"
      - "8000:8000"  # Official ocserv-exporter metrics endpoint
    
    # Конфигурации
    configs:
      - source: ocserv_config
        target: /etc/ocserv/ocserv.conf
        mode: 0644
    
    # Секреты
    secrets:
      - ocserv_passwd
      - server_cert
      - server_key
      - ca_cert
    
    # Настройки сети
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    
    # Устройства
    devices:
      - /dev/net/tun:/dev/net/tun
    
    # Sysctls для IP forwarding
    sysctls:
      - net.ipv4.ip_forward=1
    
    # Логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

configs:
  ocserv_config:
    file: ./config/ocserv.conf

secrets:
  ocserv_passwd:
    file: ./config/passwd
  server_cert:
    file: ./certs/server.crt
  server_key:
    file: ./certs/server.key
  ca_cert:
    file: ./certs/ca.crt
